# Generated by Django 5.1.15 on 2026-02-02 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('plans', '0001_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressNoteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'progress_note_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProgressNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('quick', 'Quick Note'), ('full', 'Full Note')], max_length=20)),
                ('status', models.CharField(choices=[('default', 'Active'), ('cancelled', 'Cancelled')], default='default', max_length=20)),
                ('status_reason', models.TextField(blank=True, default='')),
                ('notes_text', models.TextField(blank=True, default='', help_text='Content for quick notes.')),
                ('summary', models.TextField(blank=True, default='')),
                ('backdate', models.DateTimeField(blank=True, help_text='Override date if note is for a past session.', null=True)),
                ('begin_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_notes', to=settings.AUTH_USER_MODEL)),
                ('author_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.program')),
                ('client_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_notes', to='clients.clientfile')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.progressnotetemplate')),
            ],
            options={
                'db_table': 'progress_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressNoteTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_entries', to='plans.plantarget')),
                ('progress_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_entries', to='notes.progressnote')),
            ],
            options={
                'db_table': 'progress_note_targets',
            },
        ),
        migrations.CreateModel(
            name='MetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metric_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.metricdefinition')),
                ('progress_note_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='notes.progressnotetarget')),
            ],
            options={
                'db_table': 'metric_values',
            },
        ),
        migrations.CreateModel(
            name='ProgressNoteTemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('section_type', models.CharField(choices=[('basic', 'Basic Text'), ('plan', 'Plan Targets')], default='basic', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='notes.progressnotetemplate')),
            ],
            options={
                'db_table': 'progress_note_template_sections',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProgressNoteTemplateMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('metric_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.metricdefinition')),
                ('template_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='notes.progressnotetemplatesection')),
            ],
            options={
                'db_table': 'progress_note_template_metrics',
                'ordering': ['sort_order'],
            },
        ),
    ]
