# Generated by Django 6.0.1 on 2026-02-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_progressnote_interaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressnote',
            name='engagement_observation',
            field=models.CharField(blank=True, choices=[('', '---------'), ('disengaged', 'Disengaged'), ('motions', 'Going through the motions'), ('guarded', 'Guarded but present'), ('engaged', 'Engaged'), ('valuing', 'Valuing the process'), ('no_interaction', 'No individual interaction')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='progressnotetarget',
            name='_client_words_encrypted',
            field=models.BinaryField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='progressnotetarget',
            name='progress_descriptor',
            field=models.CharField(blank=True, choices=[('', '---------'), ('harder', 'Harder right now'), ('holding', 'Holding steady'), ('shifting', "Something's shifting"), ('good_place', 'In a good place')], default='', max_length=20),
        ),
    ]
