# Generated by Django 5.1.15 on 2026-02-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_systemhealthcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='outcome',
            field=models.CharField(blank=True, choices=[('reached', 'Reached'), ('voicemail', 'Voicemail'), ('no_answer', 'No Answer'), ('left_message', 'Left Message'), ('wrong_number', 'Wrong Number')], default='', help_text='Contact attempt result — used for funder reporting', max_length=20),
        ),
    ]
