# Generated by Django 6.0.1 on 2026-02-06 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0012_rename_receptionist_access_to_front_desk_access'),
        ('programs', '0003_alter_userprogramrole_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group_type', models.CharField(choices=[('service_group', 'Service Group'), ('activity_group', 'Activity Group'), ('project', 'Project')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='programs.program')),
            ],
            options={
                'db_table': 'groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(blank=True, default='', max_length=255)),
                ('role', models.CharField(choices=[('member', 'Member'), ('leader', 'Leader')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_memberships', to='clients.clientfile')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.group')),
            ],
            options={
                'db_table': 'group_memberships',
            },
        ),
        migrations.CreateModel(
            name='GroupSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('group_vibe', models.CharField(blank=True, choices=[('', 'Not recorded'), ('rough', 'Rough'), ('low', 'Low'), ('solid', 'Solid'), ('great', 'Great')], default='', max_length=10)),
                ('_notes_encrypted', models.BinaryField(blank=True, default=b'')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facilitator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitated_sessions', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='groups.group')),
            ],
            options={
                'db_table': 'group_sessions',
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='GroupSessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=True)),
                ('group_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='groups.groupsession')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='groups.groupmembership')),
            ],
            options={
                'db_table': 'group_session_attendance',
            },
        ),
        migrations.CreateModel(
            name='GroupSessionHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_notes_encrypted', models.BinaryField(blank=True, default=b'')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='groups.groupsession')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='groups.groupmembership')),
            ],
            options={
                'db_table': 'group_session_highlights',
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='not_started', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='groups.group')),
            ],
            options={
                'db_table': 'project_milestones',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_date', models.DateField()),
                ('description', models.TextField()),
                ('evidence', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_outcomes', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='groups.group')),
            ],
            options={
                'db_table': 'project_outcomes',
                'ordering': ['-outcome_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('client_file__isnull', False)), fields=('group', 'client_file'), name='unique_group_client_file'),
        ),
        migrations.AlterUniqueTogether(
            name='groupsessionattendance',
            unique_together={('group_session', 'membership')},
        ),
    ]
