# Generated by Django 6.0.1 on 2026-02-09 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_fix_unique_constraint_status'),
        ('groups', '0002_simplify_group_types'),
    ]

    operations = [
    ]
