# Generated by Django 6.0.1 on 2026-02-09 18:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0017_add_cross_programme_sharing_consent'),
        ('plans', '0004_metricdefinition_portal_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_hash', models.CharField(db_index=True, help_text='HMAC-SHA-256 of normalised email for constant-time lookup.', max_length=64, unique=True)),
                ('_email_encrypted', models.BinaryField(blank=True, default=b'')),
                ('display_name', models.CharField(help_text='Preferred name shown in the portal UI.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('preferred_language', models.CharField(default='en', help_text='ISO language code for portal UI.', max_length=10)),
                ('mfa_method', models.CharField(choices=[('totp', 'TOTP'), ('email', 'Email code'), ('exempt', 'Exempt')], default='totp', max_length=20)),
                ('_totp_secret_encrypted', models.BinaryField(blank=True, default=b'')),
                ('failed_login_count', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('journal_disclosure_shown', models.BooleanField(default=False, help_text='True after the participant has seen the journal privacy notice.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_account', to='clients.clientfile')),
            ],
            options={
                'verbose_name': 'participant account',
                'verbose_name_plural': 'participant accounts',
                'db_table': 'portal_participant_users',
            },
        ),
        migrations.CreateModel(
            name='ParticipantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('general', 'General'), ('pre_session', 'Pre-session')], max_length=20)),
                ('_content_encrypted', models.BinaryField(default=b'')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('client_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_messages', to='clients.clientfile')),
                ('participant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='portal.participantuser')),
            ],
            options={
                'verbose_name': 'participant message',
                'verbose_name_plural': 'participant messages',
                'db_table': 'portal_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_content_encrypted', models.BinaryField(default=b'')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_journal_entries', to='clients.clientfile')),
                ('plan_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_journal_entries', to='plans.plantarget')),
                ('participant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='portal.participantuser')),
            ],
            options={
                'verbose_name': 'journal entry',
                'verbose_name_plural': 'journal entries',
                'db_table': 'portal_journal_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('goal', 'Goal'), ('metric', 'Metric'), ('reflection', 'Reflection')], help_text='What kind of record the participant wants corrected.', max_length=20)),
                ('object_id', models.IntegerField(help_text='Primary key of the specific record to correct.')),
                ('_description_encrypted', models.BinaryField(default=b'')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('discussed', 'Discussed'), ('corrected', 'Corrected'), ('no_change', 'No change needed')], default='pending', max_length=20)),
                ('staff_response', models.TextField(blank=True, default='', help_text='Staff explanation of the correction outcome.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('client_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_correction_requests', to='clients.clientfile')),
                ('participant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='portal.participantuser')),
            ],
            options={
                'verbose_name': 'correction request',
                'verbose_name_plural': 'correction requests',
                'db_table': 'portal_correction_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', help_text='URL-safe token generated with secrets.token_urlsafe(48).', max_length=64, unique=True)),
                ('verbal_code', models.CharField(blank=True, default='', help_text='Optional 4-digit code for in-person verbal verification.', max_length=4)),
                ('consent_screens_shown', models.JSONField(blank=True, default=dict, help_text='Maps screen_id to ISO timestamp when shown.')),
                ('consent_document_version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('client_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_invites', to='clients.clientfile')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_invites_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'portal invite',
                'verbose_name_plural': 'portal invites',
                'db_table': 'portal_invites',
            },
        ),
    ]
