# Generated by Django 6.0.1 on 2026-02-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_userprogramrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogramrole',
            name='role',
            field=models.CharField(choices=[('receptionist', 'Front Desk'), ('staff', 'Direct Service'), ('program_manager', 'Program Manager'), ('executive', 'Executive')], max_length=20),
        ),
    ]
