# Generated by Django 6.0.1 on 2026-02-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_add_is_confidential'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='service_model',
            field=models.CharField(choices=[('individual', 'One-on-one'), ('group', 'Group sessions'), ('both', 'Both')], default='both', help_text='How staff record their work in this program. One-on-one: individual notes and plans. Group sessions: attendance and session notes. Both: all of the above.', max_length=20),
        ),
    ]
