# Generated by Django 6.0.1 on 2026-02-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_add_service_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='name_fr',
            field=models.CharField(blank=True, default='', help_text='French name (displayed when language is French)', max_length=255),
        ),
    ]
