# Generated by Django 6.0.1 on 2026-02-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_add_program_name_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='portal_display_name',
            field=models.CharField(blank=True, default='', help_text='Name shown in participant portal. Leave blank to use programme name.', max_length=255),
        ),
    ]
