# Generated by Django 5.1.15 on 2026-02-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_program_portal_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='portal_display_name',
            field=models.CharField(blank=True, default='', help_text='Name shown in participant portal. Leave blank to use program name.', max_length=255),
        ),
    ]
