# Generated by Django 5.1.15 on 2026-02-02 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField(help_text='What this metric measures and how to score it.')),
                ('category', models.CharField(choices=[('mental_health', 'Mental Health'), ('housing', 'Housing'), ('employment', 'Employment'), ('substance_use', 'Substance Use'), ('youth', 'Youth'), ('general', 'General'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('is_library', models.BooleanField(default=False, help_text='Part of the built-in metric library.')),
                ('is_enabled', models.BooleanField(default=True, help_text='Available for use in this instance.')),
                ('min_value', models.FloatField(blank=True, help_text='Minimum valid value.', null=True)),
                ('max_value', models.FloatField(blank=True, help_text='Maximum valid value.', null=True)),
                ('unit', models.CharField(blank=True, default='', help_text="e.g., 'score', 'days', '%'", max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'metric_definitions',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'plan_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlanSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('default', 'Active'), ('completed', 'Completed'), ('deactivated', 'Deactivated')], default='default', max_length=20)),
                ('status_reason', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_sections', to='clients.clientfile')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_sections', to='programs.program')),
            ],
            options={
                'db_table': 'plan_sections',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PlanTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('default', 'Active'), ('completed', 'Completed'), ('deactivated', 'Deactivated')], default='default', max_length=20)),
                ('status_reason', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_targets', to='clients.clientfile')),
                ('plan_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='plans.plansection')),
            ],
            options={
                'db_table': 'plan_targets',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PlanTargetMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('metric_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.metricdefinition')),
                ('plan_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plantarget')),
            ],
            options={
                'db_table': 'plan_target_metrics',
                'ordering': ['sort_order'],
                'unique_together': {('plan_target', 'metric_def')},
            },
        ),
        migrations.AddField(
            model_name='plantarget',
            name='metrics',
            field=models.ManyToManyField(blank=True, through='plans.PlanTargetMetric', to='plans.metricdefinition'),
        ),
        migrations.CreateModel(
            name='PlanTargetRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='default', max_length=20)),
                ('status_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plan_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='plans.plantarget')),
            ],
            options={
                'db_table': 'plan_target_revisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanTemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('plan_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='plans.plantemplate')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.program')),
            ],
            options={
                'db_table': 'plan_template_sections',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PlanTemplateTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('template_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='plans.plantemplatesection')),
            ],
            options={
                'db_table': 'plan_template_targets',
                'ordering': ['sort_order'],
            },
        ),
    ]
