# Generated by Django 6.0.1 on 2026-02-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantarget',
            name='_client_goal_encrypted',
            field=models.BinaryField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='plantargetrevision',
            name='_client_goal_encrypted',
            field=models.BinaryField(blank=True, default=b''),
        ),
    ]
