# Generated by Django 6.0.1 on 2026-02-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_encrypt_target_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricdefinition',
            name='portal_visibility',
            field=models.CharField(choices=[('yes', 'Visible in participant portal'), ('no', 'Hidden from participant portal'), ('self_reported', 'Only when self-reported')], default='no', help_text='Visibility in participant portal. Default: hidden until explicitly enabled.', max_length=20),
        ),
    ]
