# Generated by Django 6.0.1 on 2026-02-03 20:26

import apps.registration.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0004_consolidate_receptionist_access'),
        ('programs', '0002_alter_userprogramrole_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=apps.registration.models.generate_unique_slug, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('auto_approve', models.BooleanField(default=False, help_text='Automatically approve submissions without staff review.')),
                ('max_registrations', models.PositiveIntegerField(blank=True, help_text='Maximum number of registrations allowed (leave blank for unlimited).', null=True)),
                ('closes_at', models.DateTimeField(blank=True, help_text='Registration deadline (leave blank for no deadline).', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_registration_links', to=settings.AUTH_USER_MODEL)),
                ('field_groups', models.ManyToManyField(blank=True, help_text='Custom field groups to include on the registration form.', to='clients.customfieldgroup')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_links', to='programs.program')),
            ],
            options={
                'db_table': 'registration_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_first_name_encrypted', models.BinaryField(default=b'')),
                ('_last_name_encrypted', models.BinaryField(default=b'')),
                ('_email_encrypted', models.BinaryField(blank=True, default=b'')),
                ('_phone_encrypted', models.BinaryField(blank=True, default=b'')),
                ('email_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('field_values', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlist', 'Waitlisted')], default='pending', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('client_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_submissions', to='clients.clientfile')),
                ('registration_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='registration.registrationlink')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registration_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
