# Generated by Django 6.0.1 on 2026-02-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('export', 'Export'), ('view', 'View'), ('post', 'POST'), ('put', 'PUT'), ('patch', 'PATCH')], max_length=50),
        ),
    ]
