# Generated by Django 6.0.1 on 2026-02-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_add_is_demo_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='is_confidential_context',
            field=models.BooleanField(default=False, help_text='True when the action involved a confidential program.'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('export', 'Export'), ('view', 'View'), ('post', 'POST'), ('put', 'PUT'), ('patch', 'PATCH'), ('access_denied', 'Access Denied')], max_length=50),
        ),
    ]
