# Generated by Django 5.1.15 on 2026-02-02 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_first_name_encrypted', models.BinaryField(default=b'')),
                ('_middle_name_encrypted', models.BinaryField(blank=True, default=b'')),
                ('_last_name_encrypted', models.BinaryField(default=b'')),
                ('_birth_date_encrypted', models.BinaryField(blank=True, default=b'')),
                ('record_id', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('discharged', 'Discharged')], default='active', max_length=20)),
                ('status_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_given_at', models.DateTimeField(blank=True, null=True)),
                ('consent_type', models.CharField(blank=True, default='', max_length=50)),
                ('retention_expires', models.DateField(blank=True, null=True)),
                ('erasure_requested', models.BooleanField(default=False)),
                ('erasure_completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client_files',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'custom_field_groups',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ClientProgramEnrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('unenrolled', 'Unenrolled')], default='enrolled', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('unenrolled_at', models.DateTimeField(blank=True, null=True)),
                ('client_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='clients.clientfile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_enrolments', to='programs.program')),
            ],
            options={
                'db_table': 'client_program_enrolments',
            },
        ),
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('select', 'Dropdown'), ('date', 'Date'), ('number', 'Number')], default='text', max_length=20)),
                ('placeholder', models.CharField(blank=True, default='', max_length=255)),
                ('is_required', models.BooleanField(default=False)),
                ('is_sensitive', models.BooleanField(default=False, help_text="Encrypt this field's values.")),
                ('options_json', models.JSONField(blank=True, default=list, help_text='Options for select fields.')),
                ('sort_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='clients.customfieldgroup')),
            ],
            options={
                'db_table': 'custom_field_definitions',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ClientDetailValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='')),
                ('_value_encrypted', models.BinaryField(blank=True, default=b'')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_values', to='clients.clientfile')),
                ('field_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.customfielddefinition')),
            ],
            options={
                'db_table': 'client_detail_values',
                'unique_together': {('client_file', 'field_def')},
            },
        ),
    ]
