# Generated by Django 6.0.1 on 2026-02-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfielddefinition',
            name='receptionist_visible',
            field=models.BooleanField(default=False, help_text='Allow receptionists to see this field. Use for contact info, emergency contacts, and safety alerts.'),
        ),
    ]
