# Generated by Django 6.0.1 on 2026-02-03 19:12

from django.db import migrations, models


def migrate_receptionist_fields(apps, schema_editor):
    """Convert receptionist_visible + receptionist_editable to receptionist_access."""
    CustomFieldDefinition = apps.get_model("clients", "CustomFieldDefinition")
    for field in CustomFieldDefinition.objects.all():
        if field.receptionist_editable:
            field.receptionist_access = "edit"
        elif field.receptionist_visible:
            field.receptionist_access = "view"
        else:
            field.receptionist_access = "none"
        field.save()


def reverse_migrate(apps, schema_editor):
    """Convert receptionist_access back to two boolean fields."""
    CustomFieldDefinition = apps.get_model("clients", "CustomFieldDefinition")
    for field in CustomFieldDefinition.objects.all():
        if field.receptionist_access == "edit":
            field.receptionist_visible = True
            field.receptionist_editable = True
        elif field.receptionist_access == "view":
            field.receptionist_visible = True
            field.receptionist_editable = False
        else:
            field.receptionist_visible = False
            field.receptionist_editable = False
        field.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_add_receptionist_editable'),
    ]

    operations = [
        # Add new field first
        migrations.AddField(
            model_name='customfielddefinition',
            name='receptionist_access',
            field=models.CharField(
                choices=[('none', 'Hidden'), ('view', 'View only'), ('edit', 'View and edit')],
                default='none',
                help_text='What access receptionists have to this field.',
                max_length=10,
            ),
        ),
        # Migrate data from old fields to new field
        migrations.RunPython(migrate_receptionist_fields, reverse_migrate),
        # Remove old fields
        migrations.RemoveField(
            model_name='customfielddefinition',
            name='receptionist_editable',
        ),
        migrations.RemoveField(
            model_name='customfielddefinition',
            name='receptionist_visible',
        ),
    ]
