# Generated by Django 6.0.1 on 2026-02-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_merge_demo_and_receptionist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfielddefinition',
            name='input_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('select', 'Dropdown'), ('select_other', 'Dropdown with Other option'), ('date', 'Date'), ('number', 'Number')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='customfielddefinition',
            name='receptionist_access',
            field=models.CharField(choices=[('none', 'Hidden'), ('view', 'View only'), ('edit', 'View and edit')], default='none', help_text='What access front desk staff have to this field.', max_length=10),
        ),
    ]
