# Generated by Django 6.0.1 on 2026-02-06 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_customfielddefinition_input_type_and_more'),
        ('programs', '0003_alter_userprogramrole_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErasureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_pk', models.IntegerField(help_text='Original ClientFile PK for audit cross-reference.')),
                ('client_record_id', models.CharField(blank=True, default='', max_length=100)),
                ('data_summary', models.JSONField(default=dict)),
                ('requested_by_display', models.CharField(default='', max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reason_category', models.CharField(choices=[('client_requested', 'Client Requested'), ('retention_expired', 'Retention Period Expired'), ('discharged', 'Client Discharged'), ('other', 'Other')], default='other', max_length=30)),
                ('request_reason', models.TextField(help_text='Why this data should be erased. Do not include client names.')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved — Data Erased'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('programs_required', models.JSONField(default=list, help_text='List of program PKs that need approval before erasure executes.')),
                ('client_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erasure_requests', to='clients.clientfile')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erasure_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'erasure_requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ErasureApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_by_display', models.CharField(default='', max_length=255)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erasure_approvals_given', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.program')),
                ('erasure_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='clients.erasurerequest')),
            ],
            options={
                'db_table': 'erasure_approvals',
                'unique_together': {('erasure_request', 'program')},
            },
        ),
    ]
