# Generated by Django 6.0.1 on 2026-02-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_erasurerequest_erasureapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfielddefinition',
            name='validation_type',
            field=models.CharField(choices=[('none', 'None'), ('postal_code', 'Canadian Postal Code'), ('phone', 'Phone Number'), ('email', 'Email Address')], default='none', help_text='Determines which validation and normalisation rules apply to this field.', max_length=20),
        ),
    ]
