# Generated by Django 6.0.1 on 2026-02-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_erasure_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='erasurerequest',
            name='receipt_downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
