# Generated by Django 6.0.1 on 2026-02-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_rename_receptionist_access_to_front_desk_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfile',
            name='_phone_encrypted',
            field=models.BinaryField(blank=True, default=b''),
        ),
    ]
