# Generated by Django 6.0.1 on 2026-02-07 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_add_phone_encrypted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMerge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kept_client_pk', models.IntegerField()),
                ('archived_client_pk', models.IntegerField()),
                ('kept_record_id', models.CharField(blank=True, default='', max_length=100)),
                ('archived_record_id', models.CharField(blank=True, default='', max_length=100)),
                ('merged_by_display', models.CharField(default='', max_length=255)),
                ('merged_at', models.DateTimeField(auto_now_add=True)),
                ('transfer_summary', models.JSONField(default=dict, help_text='Counts of transferred records: {notes: 5, events: 2, ...}')),
                ('pii_choices', models.JSONField(default=dict, help_text="Which PII fields came from which client: {first_name: 'kept', phone: 'archived'}")),
                ('field_conflict_resolutions', models.JSONField(default=dict, help_text="Custom field conflict resolutions: {field_def_id: 'kept'/'archived'}")),
                ('archived_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merges_archived', to='clients.clientfile')),
                ('kept_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merges_kept', to='clients.clientfile')),
                ('merged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merges_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_merges',
                'ordering': ['-merged_at'],
            },
        ),
    ]
