# Generated by Django 6.0.1 on 2026-02-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_clientmerge'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfile',
            name='_preferred_name_encrypted',
            field=models.BinaryField(blank=True, default=b''),
        ),
    ]
