# Generated by Django 6.0.1 on 2026-02-09 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_add_preferred_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='erasurerequest',
            name='reason_category',
            field=models.CharField(choices=[('client_requested', 'Participant Requested'), ('retention_expired', 'Retention Period Expired'), ('discharged', 'Participant Discharged'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.CreateModel(
            name='ClientAccessBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Why this block exists (e.g., conflict of interest, safety concern)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_blocks', to='clients.clientfile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_access_blocks', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Access Block',
                'verbose_name_plural': 'Client Access Blocks',
                'db_table': 'client_access_blocks',
                'unique_together': {('user', 'client_file')},
            },
        ),
    ]
