# Generated by Django 6.0.1 on 2026-02-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_alter_erasurerequest_reason_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfile',
            name='cross_programme_sharing_consent',
            field=models.BooleanField(default=False, help_text='Client has given express consent for clinical information to be shared across programmes. Required under PHIPA for multi-programme agencies.'),
        ),
    ]
