# Generated by Django 6.0.1 on 2026-02-08 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_secure_export_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, help_text='Format: insights:{program_id}:{date_from}:{date_to} or insights:client:{client_id}:{date_from}:{date_to}', max_length=255, unique=True)),
                ('summary_json', models.JSONField(help_text='Full validated AI response: summary, themes, cited_quotes, recommendations.')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'insight_summaries',
                'ordering': ['-generated_at'],
            },
        ),
    ]
