# Generated by Django 5.1.15 on 2026-02-12 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_staffportalnote'),
        ('programs', '0008_funder_profiles'),
        ('reports', '0004_rename_cmt_to_funder_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='secureexportlink',
            name='export_type',
            field=models.CharField(choices=[('client_data', 'Participant Data'), ('metrics', 'Metric Report'), ('funder_report', 'Funder Report')], max_length=50),
        ),
        migrations.CreateModel(
            name='FunderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Funder name, e.g., 'United Way Greater Toronto'.", max_length=255)),
                ('description', models.TextField(blank=True, help_text="Description of the reporting requirements, e.g., 'Annual Community Impact Report'.")),
                ('source_csv', models.TextField(blank=True, help_text='Original uploaded CSV content, preserved for re-export and audit.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_funder_profiles', to=settings.AUTH_USER_MODEL)),
                ('programs', models.ManyToManyField(blank=True, help_text='Programs that report to this funder.', related_name='funder_profiles', to='programs.program')),
            ],
            options={
                'db_table': 'funder_profiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DemographicBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Display label, e.g., 'Age Group' or 'Employment Status'.", max_length=100)),
                ('source_type', models.CharField(choices=[('age', 'Age (from date of birth)'), ('custom_field', 'Custom intake field')], max_length=20)),
                ('bins_json', models.JSONField(blank=True, default=list, help_text='For age breakdowns: list of {"min": int, "max": int, "label": str}. E.g., [{"min": 0, "max": 14, "label": "Child (0-14)"}]')),
                ('merge_categories_json', models.JSONField(blank=True, default=dict, help_text='For custom field breakdowns: map target labels to lists of source labels. E.g., {"Employed": ["Employed full-time", "Employed part-time"]}')),
                ('keep_all_categories', models.BooleanField(default=False, help_text="Use the field's original categories without merging.")),
                ('sort_order', models.IntegerField(default=0)),
                ('custom_field', models.ForeignKey(blank=True, help_text='The intake field to group by (only for custom_field source type).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.customfielddefinition')),
                ('funder_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='reports.funderprofile')),
            ],
            options={
                'db_table': 'demographic_breakdowns',
                'ordering': ['sort_order'],
            },
        ),
    ]
